workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - npm install
      - npx react-native run-ios --configuration Release
    artifacts:
      - build/ios/ipa/*.ipa